#!/usr/sbin/nft -f

# Base nftables config — will be overwritten by netfilterd

flush ruleset

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oifname "eth1" masquerade
    }
}

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state established,related accept
        iif lo accept
        iifname "wlan0" udp dport 53 accept
        iifname "wlan0" udp dport 67 accept
        iifname "wlan0" tcp dport 22 accept
        iifname "wlan0" tcp dport 8443 accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
        # All client traffic blocked by default
        # netfilterd adds accept rules here
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
