package services

import (
	"bufio"
	"database/sql"
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	"github.com/iulianfsdro/rpi-network-filter/internal/executor"
	"github.com/iulianfsdro/rpi-network-filter/internal/models"
)

type DNSService struct {
	db      *sql.DB
	exec    *executor.Executor
	blocked *BlockedService
	mu      sync.Mutex
}

func NewDNSService(db *sql.DB, exec *executor.Executor, blocked *BlockedService) *DNSService {
	return &DNSService{db: db, exec: exec, blocked: blocked}
}

func (s *DNSService) ListEntries() ([]models.DNSBlockEntry, error) {
	rows, err := s.db.Query(`
		SELECT id, domain, category, enabled, created_at
		FROM dns_blocklist ORDER BY domain ASC
	`)
	if err != nil {
		return nil, fmt.Errorf("query dns blocklist: %w", err)
	}
	defer rows.Close()

	var entries []models.DNSBlockEntry
	for rows.Next() {
		var e models.DNSBlockEntry
		var enabled int
		if err := rows.Scan(&e.ID, &e.Domain, &e.Category, &enabled, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan dns entry: %w", err)
		}
		e.Enabled = enabled == 1
		entries = append(entries, e)
	}
	return entries, nil
}

func (s *DNSService) CreateEntry(domain, category string) (int64, error) {
	domain = NormalizeDomain(domain)
	if domain == "" {
		return 0, fmt.Errorf("invalid domain — must be a plain hostname")
	}
	if category == "" {
		category = "custom"
	}
	result, err := s.db.Exec(
		"INSERT INTO dns_blocklist (domain, category) VALUES (?, ?)",
		domain, category,
	)
	if err != nil {
		return 0, fmt.Errorf("insert dns entry: %w", err)
	}
	return result.LastInsertId()
}

func (s *DNSService) DeleteEntry(id int64) error {
	_, err := s.db.Exec("DELETE FROM dns_blocklist WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete dns entry %d: %w", id, err)
	}
	return nil
}

func (s *DNSService) ToggleEntry(id int64, enabled bool) error {
	e := 0
	if enabled {
		e = 1
	}
	_, err := s.db.Exec("UPDATE dns_blocklist SET enabled = ? WHERE id = ?", e, id)
	if err != nil {
		return fmt.Errorf("toggle dns entry %d: %w", id, err)
	}
	return nil
}

func (s *DNSService) ImportDomains(text, category string) (int, error) {
	if category == "" {
		category = "imported"
	}

	scanner := bufio.NewScanner(strings.NewReader(text))
	count := 0

	tx, err := s.db.Begin()
	if err != nil {
		return 0, fmt.Errorf("begin import tx: %w", err)
	}

	stmt, err := tx.Prepare("INSERT OR IGNORE INTO dns_blocklist (domain, category) VALUES (?, ?)")
	if err != nil {
		tx.Rollback()
		return 0, fmt.Errorf("prepare import stmt: %w", err)
	}
	defer stmt.Close()

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Handle hosts file format: "0.0.0.0 domain.com" or "127.0.0.1 domain.com"
		fields := strings.Fields(line)
		var domain string
		if len(fields) >= 2 && (fields[0] == "0.0.0.0" || fields[0] == "127.0.0.1") {
			domain = fields[1]
		} else if len(fields) == 1 {
			domain = fields[0]
		} else {
			continue
		}

		domain = strings.ToLower(strings.TrimSpace(domain))
		if domain == "" || domain == "localhost" || domain == "localhost.localdomain" {
			continue
		}

		if _, err := stmt.Exec(domain, category); err == nil {
			count++
		}
	}

	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("commit import: %w", err)
	}

	return count, nil
}

func (s *DNSService) GetCount() (int, error) {
	var count int
	err := s.db.QueryRow("SELECT COUNT(*) FROM dns_blocklist WHERE enabled = 1").Scan(&count)
	return count, err
}

func (s *DNSService) Apply() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	rows, err := s.db.Query("SELECT domain FROM dns_blocklist WHERE enabled = 1")
	if err != nil {
		return fmt.Errorf("query enabled domains: %w", err)
	}
	defer rows.Close()

	var b strings.Builder
	b.WriteString("# Generated by netfilterd — do not edit\n")

	count := 0
	for rows.Next() {
		var domain string
		rows.Scan(&domain)
		fmt.Fprintf(&b, "address=/%s/0.0.0.0\n", domain)
		count++
	}

	// Hard-blocked domains (e.g. Tesla firmware endpoints) — sinkholed to
	// 0.0.0.0 so they fail to resolve even if the nftables allow-list is
	// somehow bypassed. dnsmasq's address= directive is suffix-matching,
	// so "address=/tesla-cdn.com/0.0.0.0" also sinkholes "x.tesla-cdn.com".
	if s.blocked != nil {
		b.WriteString("\n# Hard-blocked domains (never resolve)\n")
		hard, err := s.blocked.EnabledDomains()
		if err != nil {
			log.Printf("[WARN] Failed to read blocked domains: %v", err)
		}
		for _, d := range hard {
			domain := NormalizeDomain(d.Domain)
			if domain == "" {
				continue
			}
			// dnsmasq matches suffix natively; for 'exact' we still emit the
			// same form because there's no narrower dnsmasq directive — the
			// exact/suffix distinction is enforced at the allow-list guard.
			fmt.Fprintf(&b, "address=/%s/0.0.0.0\n", domain)
			count++
		}
	}

	confPath := "/etc/dnsmasq.d/blocklist.conf"
	if err := os.WriteFile(confPath, []byte(b.String()), 0644); err != nil {
		if !s.exec.DryRun {
			return fmt.Errorf("write %s: %w", confPath, err)
		}
		log.Printf("[DRY-RUN] Would write %s (%d entries)", confPath, count)
	}

	if _, err := s.exec.Run("systemctl", "reload", "dnsmasq"); err != nil {
		return fmt.Errorf("reload dnsmasq: %w", err)
	}

	log.Printf("[DNS] Applied blocklist with %d domains", count)
	return nil
}
