package services

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	"github.com/iulianfsdro/rpi-network-filter/internal/executor"
)

type HotspotService struct {
	db   *sql.DB
	exec *executor.Executor
	mu   sync.Mutex
}

func NewHotspotService(db *sql.DB, exec *executor.Executor) *HotspotService {
	return &HotspotService{db: db, exec: exec}
}

func (s *HotspotService) Apply() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	settings := s.getSettings()

	var b strings.Builder
	b.WriteString("# Generated by netfilterd — do not edit\n")
	b.WriteString("interface=wlan0\n")
	b.WriteString("driver=nl80211\n")
	fmt.Fprintf(&b, "ssid=%s\n", settings["ap_ssid"])
	b.WriteString("hw_mode=g\n")
	fmt.Fprintf(&b, "channel=%s\n", settings["ap_channel"])
	b.WriteString("wmm_enabled=0\n")
	b.WriteString("macaddr_acl=0\n")
	b.WriteString("auth_algs=1\n")
	b.WriteString("ignore_broadcast_ssid=0\n")
	b.WriteString("wpa=2\n")
	fmt.Fprintf(&b, "wpa_passphrase=%s\n", settings["ap_password"])
	b.WriteString("wpa_key_mgmt=WPA-PSK\n")
	b.WriteString("wpa_pairwise=TKIP\n")
	b.WriteString("rsn_pairwise=CCMP\n")

	confPath := "/etc/hostapd/hostapd.conf"
	if err := os.WriteFile(confPath, []byte(b.String()), 0644); err != nil {
		if !s.exec.DryRun {
			return fmt.Errorf("write %s: %w", confPath, err)
		}
		log.Printf("[DRY-RUN] Would write %s", confPath)
	}

	if _, err := s.exec.Run("systemctl", "restart", "hostapd"); err != nil {
		return fmt.Errorf("restart hostapd: %w", err)
	}

	log.Printf("[HOTSPOT] Applied config: SSID=%s, channel=%s", settings["ap_ssid"], settings["ap_channel"])
	return nil
}

func (s *HotspotService) getSettings() map[string]string {
	defaults := map[string]string{
		"ap_ssid":     "NetFilter",
		"ap_password": "changeme123",
		"ap_channel":  "6",
	}

	rows, err := s.db.Query("SELECT key, value FROM settings WHERE key IN ('ap_ssid', 'ap_password', 'ap_channel')")
	if err != nil {
		return defaults
	}
	defer rows.Close()

	for rows.Next() {
		var k, v string
		rows.Scan(&k, &v)
		defaults[k] = v
	}
	return defaults
}
