package services

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/iulianfsdro/rpi-network-filter/internal/config"
)

// Tesla MCU3 polls connman.vn.tesla.services as its captive-portal /
// connectivity probe. It declares the WiFi link "online" only when it
// gets a 200 OK with these specific headers (the real endpoint sits
// behind CloudFront, hence the X-Cache marker).
const (
	spoofConnManHost = "connman.vn.tesla.services"
	spoofDnsmasqPath = "/etc/dnsmasq.d/netfilter-spoof.conf"
)

var spoofConnManHeaders = map[string]string{
	"X-ConnMan-Status": "online",
	"X-Cache":          "Hit from cloudfront",
}

// SpoofService runs a tiny HTTP responder that intercepts captive-check
// probes (currently just Tesla connman). It pairs with a dnsmasq
// address= override that resolves the spoofed hostname to the Pi's LAN
// gateway so the probe lands on us instead of going out to the real
// origin.
type SpoofService struct {
	cfg config.Config
}

func NewSpoofService(cfg config.Config) *SpoofService {
	return &SpoofService{cfg: cfg}
}

// WriteDnsmasqConf writes /etc/dnsmasq.d/netfilter-spoof.conf with one
// address= override per spoofed hostname pointing at cfg.LANGateway.
// Idempotent. Called once at startup before FirewallService.Apply()
// triggers `systemctl reload dnsmasq`, so dnsmasq picks the file up
// without an explicit reload here.
func (s *SpoofService) WriteDnsmasqConf() error {
	gw := strings.TrimSpace(s.cfg.LANGateway)
	if net.ParseIP(gw) == nil {
		return fmt.Errorf("invalid lan_gateway %q", s.cfg.LANGateway)
	}

	var b strings.Builder
	b.WriteString("# Generated by netfilterd — do not edit\n")
	b.WriteString("# Captive-check spoof: resolve these hostnames to the Pi so the\n")
	b.WriteString("# in-process spoof responder can answer them locally.\n\n")
	fmt.Fprintf(&b, "address=/%s/%s\n", spoofConnManHost, gw)

	if err := os.WriteFile(spoofDnsmasqPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", spoofDnsmasqPath, err)
	}
	return nil
}

// ListenAndServe binds tcp/80 on cfg.LANGateway and answers connman
// probes. Anything not matching a known spoof Host header gets 404 so
// an accidental probe to the Pi's port 80 doesn't leak anything.
// Blocks; intended to run in its own goroutine.
func (s *SpoofService) ListenAndServe() error {
	addr := net.JoinHostPort(s.cfg.LANGateway, "80")

	mux := http.NewServeMux()
	mux.HandleFunc("/", s.handle)

	srv := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       30 * time.Second,
	}

	log.Printf("[SPOOF] captive-check responder listening on http://%s (host %s)", addr, spoofConnManHost)
	return srv.ListenAndServe()
}

func (s *SpoofService) handle(w http.ResponseWriter, r *http.Request) {
	host := strings.ToLower(strings.TrimSpace(r.Host))
	// Strip an optional :port suffix — Host header normally won't carry
	// one for plain HTTP on port 80, but be defensive.
	if h, _, err := net.SplitHostPort(host); err == nil {
		host = h
	}

	if host != spoofConnManHost {
		http.NotFound(w, r)
		return
	}

	for k, v := range spoofConnManHeaders {
		w.Header().Set(k, v)
	}
	w.WriteHeader(http.StatusOK)
	log.Printf("[SPOOF] %s %s %s → 200 (client=%s)", r.Method, host, r.URL.Path, r.RemoteAddr)
}
