#!/bin/bash
# Provision a real Let's Encrypt cert via acme.sh + DNS-01 through DuckDNS.
# Result: every device on the hotspot (including Tesla's Chromium) trusts
# https://<hostname>:8443 out of the box — no CA install required.
#
# Prereqs you set up outside the script:
#   1. Create a free account at https://www.duckdns.org
#   2. Pick a subdomain (e.g. "my-netfilter" → my-netfilter.duckdns.org)
#   3. Copy the DuckDNS token from the top of the dashboard
#
# Usage on the Pi (NOT on your laptop — acme.sh lives on the Pi):
#   sudo bash /tmp/setup-letsencrypt.sh my-netfilter.duckdns.org <duckdns-token>
#
# What it does:
#   - Installs acme.sh (socat + curl only, no Python)
#   - Issues a real cert for <hostname> via DuckDNS DNS-01
#   - Deploys cert to /etc/netfilterd/server.{crt,key}
#   - Adds a dnsmasq override so LAN clients resolve <hostname> → 192.168.4.1
#   - Sets up auto-renewal with a post-renew hook that restarts netfilterd

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo $0 <hostname> <duckdns-token>"
[[ $# -eq 2 ]] || error "Usage: $0 <hostname.duckdns.org> <duckdns-token>"

HOSTNAME="$1"
DUCKDNS_TOKEN="$2"
CERT_DIR=/etc/netfilterd
PI_LAN_IP=192.168.4.1

# Paranoid: confirm the hostname actually looks like a DuckDNS address.
if [[ "$HOSTNAME" != *.duckdns.org ]]; then
    warn "Hostname $HOSTNAME doesn't end in .duckdns.org — proceeding anyway,"
    warn "but make sure your DNS provider really is DuckDNS."
fi

# --- Point the DuckDNS A record at 192.168.4.1 so clients on the hotspot
# resolve the name internally via our dnsmasq. (DuckDNS will still resolve
# the public DNS name to whatever public IP they happen to see, but that's
# harmless — we override locally.) If you'd rather not advertise the LAN
# IP on public DNS, skip this update.
info "Updating DuckDNS A record to $PI_LAN_IP (for archival only; we override via dnsmasq)"
curl -fsS "https://www.duckdns.org/update?domains=${HOSTNAME%%.duckdns.org}&token=${DUCKDNS_TOKEN}&ip=${PI_LAN_IP}" \
    -o /tmp/duckdns.out || warn "DuckDNS update failed — continuing anyway"
cat /tmp/duckdns.out; echo

# --- Install acme.sh (pure-shell ACME client, no Python or Go deps) -----

if [[ ! -d /root/.acme.sh ]]; then
    info "Installing acme.sh"
    apt-get install -y socat curl >/dev/null
    curl -fsS https://get.acme.sh | sh -s email=admin@${HOSTNAME}
fi

ACME=/root/.acme.sh/acme.sh

# --- Issue the cert via DuckDNS DNS-01 --------------------------------------

info "Issuing Let's Encrypt cert for $HOSTNAME via DuckDNS DNS-01"
export DuckDNS_Token="$DUCKDNS_TOKEN"
$ACME --set-default-ca --server letsencrypt
$ACME --issue --dns dns_duckdns -d "$HOSTNAME" --keylength 2048

# --- Deploy to netfilterd --------------------------------------------------

info "Deploying cert to $CERT_DIR"
mkdir -p "$CERT_DIR"
$ACME --install-cert -d "$HOSTNAME" \
    --key-file       "$CERT_DIR/server.key" \
    --fullchain-file "$CERT_DIR/server.crt" \
    --reloadcmd      "systemctl reload-or-restart netfilterd"

chmod 600 "$CERT_DIR/server.key"
chmod 644 "$CERT_DIR/server.crt"

# --- dnsmasq override so LAN clients resolve HOSTNAME → 192.168.4.1 ---------

info "Adding dnsmasq override: $HOSTNAME → $PI_LAN_IP"
cat > /etc/dnsmasq.d/netfilter-hostname.conf <<EOF
# Generated by setup-letsencrypt.sh — do not edit
address=/${HOSTNAME}/${PI_LAN_IP}
EOF
systemctl reload dnsmasq

# --- Restart netfilterd to pick up the new cert -----------------------------

info "Restarting netfilterd"
systemctl restart netfilterd

# --- acme.sh auto-renew cron ------------------------------------------------

if ! crontab -l 2>/dev/null | grep -q "acme.sh --cron"; then
    info "Installing acme.sh renewal cron (daily 03:17)"
    (crontab -l 2>/dev/null; echo "17 3 * * * \"$ACME\" --cron --home /root/.acme.sh >/var/log/acme-renew.log 2>&1") | crontab -
fi

echo ""
echo "================================================"
echo "  Let's Encrypt deployment complete"
echo "================================================"
echo ""
echo "  Hostname:   https://${HOSTNAME}:8443"
echo "  Cert:       $CERT_DIR/server.crt"
echo "  Key:        $CERT_DIR/server.key"
echo "  Auto-renew: $ACME --cron (cron installed)"
echo ""
echo "Test from any device on the NetFilter hotspot:"
echo "  https://${HOSTNAME}:8443/"
echo ""
echo "No cert warnings should appear — the cert is signed by Let's Encrypt."
